### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by janscholten** [dustinvtran/bayesrl#10]
I'm interested in running the code and play around a bit, but I can't get things to work when following this procedure of bash commands

1. (Creating an anaconda env with python 3.6 Ubuntu 18: `mkdir testdir`, `conda create -n testenv`, `source activate testenv`, `cd testdir`)
2. `pip install -e "git+https://github.com/dustinvtran/bayesrl.git#egg=bayesrl"`
This will actually crash in a first run:
>FileNotFoundError: [Errno 2] No such file or directory: '/home/jan/anaconda3/lib/python3.6/site-packages/bayesrl-0.1-py3.6.egg'
But a second time it installs:
`pip install -e "git+https://github.com/dustinvtran/bayesrl.git#egg=bayesrl"`
>Obtaining bayesrl from git+https://github.com/dustinvtran/bayesrl.git#egg=bayesrl
  Updating ./src/bayesrl clone
Installing collected packages: bayesrl
  Found existing installation: bayesrl 0.1
    Uninstalling bayesrl-0.1:
      Successfully uninstalled bayesrl-0.1
  Running setup.py develop for bayesrl
Successfully installed bayesrl

Then, I can succesfully output a gridworld by running `python src/bayesrl/tests/gridworld.py`
Unfortunately, other programs such as tests/thompsongridworld.py fail:
> python src/bayesrl/tests/thompsongridworld.py 
Traceback (most recent call last):
  File "src/bayesrl/tests/thompsongridworld.py", line 6, in <module>
    from bayesrl.agents.thompsonsampagent import ThompsonSampAgent
  File "/home/jan/thesis/bayesian/testdir/src/bayesrl/bayesrl/agents/thompsonsampagent.py", line 1, in <module>
    from modelbasedagent import ModelBasedAgent
ModuleNotFoundError: No module named 'modelbasedagent'

And the same error is given for e.g. benchmarks/thompson_gridworld.
Encouraged by its name, I then try 
3. `cd src/bayesrl/` 
`python setup.py build`
`python setup.py install`

Unfortunately, this does not resolve the import issues:

`python tests/thompsongridworld.py`:
>File "tests/thompsongridworld.py", line 6, in <module>
    from bayesrl.agents.thompsonsampagent import ThompsonSampAgent
  File "/home/jan/thesis/bayesian/testdir/src/bayesrl/bayesrl/agents/thompsonsampagent.py", line 1, in <module>
    from modelbasedagent import ModelBasedAgent
ModuleNotFoundError: No module named 'modelbasedagent'

Worse, also gridworld is down now:
>10:41 $ python tests/gridworld.py
Traceback (most recent call last):
  File "tests/gridworld.py", line 4, in <module>
    from bayesrl.environments import GridWorld
ModuleNotFoundError: No module named 'bayesrl.environments'

I tried many installs/reinstalls and calls from different paths but I cannot resolve these issues. I wonder if these problems are known/recognised/reproducable, and what installation procedure to follow.

A pastebin of the above is found at https://pastebin.com/7CkAEymi

Best regards, Jan

**Comment by paulshuva** [comment]
> I'm interested in running the code and play around a bit, but I can't get things to work when following this procedure of bash commands
> 
> 1. (Creating an anaconda env with python 3.6 Ubuntu 18: `mkdir testdir`, `conda create -n testenv`, `source activate testenv`, `cd testdir`)
> 2. `pip install -e "git+https://github.com/dustinvtran/bayesrl.git#egg=bayesrl"`
>    This will actually crash in a first run:
> 
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/jan/anaconda3/lib/python3.6/site-packages/bayesrl-0.1-py3.6.egg'
> > But a second time it installs:
> > `pip install -e "git+https://github.com/dustinvtran/bayesrl.git#egg=bayesrl"`
> > Obtaining bayesrl from git+https://github.com/dustinvtran/bayesrl.git#egg=bayesrl
> > Updating ./src/bayesrl clone
> > Installing collected packages: bayesrl
> > Found existing installation: bayesrl 0.1
> > Uninstalling bayesrl-0.1:
> > Successfully uninstalled bayesrl-0.1
> > Running setup.py develop for bayesrl
> > Successfully installed bayesrl
> 
> Then, I can succesfully output a gridworld by running `python src/bayesrl/tests/gridworld.py`
> Unfortunately, other programs such as tests/thompsongridworld.py fail:
> 
> > python src/bayesrl/tests/thompsongridworld.py
> > Traceback (most recent call last):
> > File "src/bayesrl/tests/thompsongridworld.py", line 6, in 
> > from bayesrl.agents.thompsonsampagent import ThompsonSampAgent
> > File "/home/jan/thesis/bayesian/testdir/src/bayesrl/bayesrl/agents/thompsonsampagent.py", line 1, in 
> > from modelbasedagent import ModelBasedAgent
> > ModuleNotFoundError: No module named 'modelbasedagent'
> 
> And the same error is given for e.g. benchmarks/thompson_gridworld.
> Encouraged by its name, I then try
> 3. `cd src/bayesrl/`
> `python setup.py build`
> `python setup.py install`
> 
> Unfortunately, this does not resolve the import issues:
> 
> `python tests/thompsongridworld.py`:
> 
> > File "tests/thompsongridworld.py", line 6, in 
> > from bayesrl.agents.thompsonsampagent import ThompsonSampAgent
> > File "/home/jan/thesis/bayesian/testdir/src/bayesrl/bayesrl/agents/thompsonsampagent.py", line 1, in 
> > from modelbasedagent import ModelBasedAgent
> > ModuleNotFoundError: No module named 'modelbasedagent'
> 
> Worse, also gridworld is down now:
> 
> > 10:41 $ python tests/gridworld.py
> > Traceback (most recent call last):
> > File "tests/gridworld.py", line 4, in 
> > from bayesrl.environments import GridWorld
> > ModuleNotFoundError: No module named 'bayesrl.environments'
> 
> I tried many installs/reinstalls and calls from different paths but I cannot resolve these issues. I wonder if these problems are known/recognised/reproducable, and what installation procedure to follow.
> 
> A pastebin of the above is found at https://pastebin.com/7CkAEymi
> 
> Best regards, Jan

Hi Jan! 

I am experiencing the same problem. Did you find the solution? 


Shuva
